pipeline:
  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/elb-healthcheck
    tag:
      - '${DRONE_BRANCH/master/latest}'
      - '${DRONE_BRANCH}.${DRONE_BUILD_NUMBER}'
#    storage_driver: overlay
